#!/bin/zsh
# Copyright (c) 2018 Raphael Scholer
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Set terminal emulator title.

emulate -L zsh

local TITLE
local TYPE
local string_ctrl
local string_format

TYPE="${1}"
STRING="${2}"

[[ "${TERM}" == (dumb|linux|*bsd*|eterm*) ]] && return 1

case "${TYPE}" in
	multiplexer )   [[ "${TERM}" != screen* ]] && return 0
	                string_ctrl='\ek%s\e\\'
	                string_format='%s'
	                ;;
	tab )           string_ctrl='\e]1;%s\a'
	                string_format='%0(a..%m: )%s'
	                ;;
	window )        string_ctrl='\e]2;%s\a'
	                string_format='%0(a..%m: )%s'
	                ;;
esac

zformat -f TITLE "${string_format}" "a:${SSH_CONNECTION}" "s:${STRING}"

printf "${string_ctrl}" "${(V%)TITLE}"

return 0
