#!/bin/zsh
# Copyright (c) 2018 Raphael Scholer
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Helper function for loading of external plugins.

emulate -L zsh

function zpm_load() {
	emulate -L zsh

	local    PLUGIN
	local -a PLUGIN_FILES
	local    PLUGIN_ROOT

	PLUGIN="${1}"
	PLUGIN_ROOT="${ZDATADIR}/plugins"

	PLUGIN_FILE=("${PLUGIN_ROOT}/${PLUGIN}"/*.plugin.zsh(.,@N))

	if [[ -n ${PLUGIN_FILE} ]]; then
		source "${PLUGIN_FILE[1]}"
	fi
}

function zpm_update() {
	emulate -L zsh

	local PLUGIN_ROOT
	local PRINT_NEWLINE
	local plugin

	PLUGIN_ROOT="${ZDATADIR}/plugins/${PLUGIN}"

	for plugin in "${PLUGIN_ROOT}"/*(FN); do
		print -P "${PRINT_NEWLINE:+\n}%F{blue}%B::%f%b ${plugin:t}"

		(cd "${plugin}"; git pull --prune)

		PRINT_NEWLINE=1
	done
}

function zpm() {
	emulate -L zsh

	local ACTION

	ACTION="${1}"

	if [[ "${ACTION}" == ('load'|'update') ]]; then
		"zpm_${ACTION}" ${@[2,-1]}
	else
		print "Unknown action: ${ACTION}"
	fi
}

zpm "${@}"
