#!/bin/zsh
# Copyright (c) 2018 Raphael Scholer
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Display arrows indicating, whether or not git repo is ahead and/or behind
# upstream.

emulate -L zsh

local    arrow_status
local -A arrow_symbol

arrow_status=''
arrow_symbol=(
	# Direction     # Symbol
	'up'            $'\u21e1'
	'down'          $'\u21e3'
)

# Make sure that we run this hook as few times as possible.
[[ "${vcs}" == git* ]] || return 1
[[ "${hook_com[misc]}" != *${arrow_symbol[up]}* ]] || return 1
[[ "${hook_com[misc]}" != *${arrow_symbol[down]}* ]] || return 1

# Get ahead/behind information and convert it to a simple array.
arrow_status="$(git rev-list --left-right --count 'HEAD...@{u}' 2>/dev/null)"

arrow_status=(${(ps:\t:)arrow_status})

# Amend misc. string.
[[ ${arrow_status[1]} -gt 0 ]] && hook_com[misc]+=${arrow_symbol[up]}
[[ ${arrow_status[2]} -gt 0 ]] && hook_com[misc]+=${arrow_symbol[down]}

return 0
